Reference: https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf

## Variable lookup tables

The codebook screenshots in `data/variable_meaning` document the source BRFSS fields. The tables below translate those fields to the cleaned column names and values used in this dataset. Binary variables use the cleaned 0/1 encoding; special nonresponse codes removed during cleaning do not appear. Continuous fields are described by their units/ranges instead of assigning a label to every observed value. `Meaning` is paired with `State` from the dataset and the BRFSS state FIPS codebook.

In [2]:
import pandas as pd
from IPython.display import display, Markdown
from pathlib import Path

In [3]:
DATA_DIR = '../../data/'

In [4]:
def create_state_df():
    state_df = pd.DataFrame([
        {"Code / value": 1, "Meaning": "Alabama"},
        {"Code / value": 2, "Meaning": "Alaska"},
        {"Code / value": 4, "Meaning": "Arizona"},
        {"Code / value": 5, "Meaning": "Arkansas"},      
        {"Code / value": 6, "Meaning": "California"},
        {"Code / value": 8, "Meaning": "Colorado"},
        {"Code / value": 9, "Meaning": "Connecticut"},
        {"Code / value": 10, "Meaning": "Delaware"},
        {"Code / value": 11, "Meaning": "District of Columbia"},
        {"Code / value": 12, "Meaning": "Florida"},
        {"Code / value": 13, "Meaning": "Georgia"},
        {"Code / value": 15, "Meaning": "Hawaii"},
        {"Code / value": 16, "Meaning": "Idaho"},
        {"Code / value": 17, "Meaning": "Illinois"},
        {"Code / value": 18, "Meaning": "Indiana"},
        {"Code / value": 19, "Meaning": "Iowa"},
        {"Code / value": 20, "Meaning": "Kansas"},
        {"Code / value": 21, "Meaning": "Kentucky"},
        {"Code / value": 22, "Meaning": "Louisiana"},
        {"Code / value": 23, "Meaning": "Maine"},
        {"Code / value": 24, "Meaning": "Maryland"},
        {"Code / value": 25, "Meaning": "Massachusetts"},
        {"Code / value": 26, "Meaning": "Michigan"},
        {"Code / value": 27, "Meaning": "Minnesota"},
        {"Code / value": 28, "Meaning": "Mississippi"},
        {"Code / value": 29, "Meaning": "Missouri"},
        {"Code / value": 30, "Meaning": "Montana"},
        {"Code / value": 31, "Meaning": "Nebraska"},
        {"Code / value": 32, "Meaning": "Nevada"},
        {"Code / value": 33, "Meaning": "New Hampshire"},
        {"Code / value": 34, "Meaning": "New Jersey"},
        {"Code / value": 35, "Meaning": "New Mexico"},
        {"Code / value": 36, "Meaning": "New York"},
        {"Code / value": 37, "Meaning": "North Carolina"},
        {"Code / value": 38, "Meaning": "North Dakota"},
        {"Code / value": 39, "Meaning": "Ohio"},
        {"Code / value": 40, "Meaning": "Oklahoma"},
        {"Code / value": 41, "Meaning": "Oregon"},
        {"Code / value": 42, "Meaning": "Pennsylvania"},
        {"Code / value": 44, "Meaning": "Rhode Island"},
        {"Code / value": 45, "Meaning": "South Carolina"},
        {"Code / value": 46, "Meaning": "South Dakota"},
        {"Code / value": 47, "Meaning": "Tennessee"},
        {"Code / value": 48, "Meaning": "Texas"},
        {"Code / value": 49, "Meaning": "Utah"},
        {"Code / value": 50, "Meaning": "Vermont"},
        {"Code / value": 51, "Meaning": "Virginia"},
        {"Code / value": 53, "Meaning": "Washington"},
        {"Code / value": 54, "Meaning": "West Virginia"},
        {"Code / value": 55, "Meaning": "Wisconsin"},
        {"Code / value": 56, "Meaning": "Wyoming"},
        {"Code / value": 66, "Meaning": "Guam"},
        {"Code / value": 72, "Meaning": "Puerto Rico"}
    ])
    return state_df

In [5]:
# Labels reflect the cleaned values. Source definitions are based on the
# corresponding codebook images in ../../data/variable_meaning/.
variable_lookups = {
    'HeartDiseaseorAttack': {0: 'No reported coronary heart disease or myocardial infarction', 1: 'Reported coronary heart disease or myocardial infarction'},
    'HighBP': {0: 'No', 1: 'Yes'},
    'HighChol': {0: 'No', 1: 'Yes'},
    'CholCheck': {0: 'No cholesterol check in the past 5 years / never checked', 1: 'Cholesterol checked within the past 5 years'},
    'BMI': {'numeric': 'Body mass index in kg/m²; source _BMI5 is divided by 100'},
    'BMICategory': {'Underweight': 'BMI < 18.5', 'Normal': '18.5 ≤ BMI < 25', 'Overweight': '25 ≤ BMI < 30', 'Obesity': 'BMI ≥ 30'},
    'Smoker': {0: 'No: has not smoked at least 100 cigarettes in lifetime', 1: 'Yes: has smoked at least 100 cigarettes in lifetime'},
    'Stroke': {0: 'No', 1: 'Yes'},
    'Diabetes': {0: 'No diabetes, or diabetes only during pregnancy', 1: 'Pre-diabetes or borderline diabetes', 2: 'Yes, diabetes'},
    'PhysActivity': {0: 'No physical activity/exercise in past 30 days outside regular job', 1: 'Any physical activity/exercise in past 30 days outside regular job'},
    'Fruits': {0: 'Fruit less than once per day', 1: 'Fruit at least once per day'},
    'Veggies': {0: 'Vegetables less than once per day', 1: 'Vegetables at least once per day'},
    'HvyAlcoholConsump': {0: 'No heavy drinking', 1: 'Heavy drinking (men >14 drinks/week; women >7 drinks/week)'},
    'AnyHealthcare': {0: 'No health-care coverage', 1: 'Has health-care coverage'},
    'NoDocbcCost': {0: 'Did not need to see a doctor but could not afford it: No', 1: 'Could not afford to see a doctor in past 12 months: Yes'},
    'GenHlth': {1: 'Excellent', 2: 'Very good', 3: 'Good', 4: 'Fair', 5: 'Poor'},
    'MentHlth': {'0': '0 days mental health not good (none)', '1–30': 'Number of days mental health was not good in the past 30 days', '88': 'None', '77': 'Don\'t know/Not sure', '99': 'Refused'},
    'PhysHlth': {'0': '0 days physical health not good (none)', '1–30': 'Number of days physical health was not good in the past 30 days', '88': 'None', '77': 'Don\'t know/Not sure', '99': 'Refused'},
    'DiffWalk': {0: 'No serious difficulty walking or climbing stairs', 1: 'Serious difficulty walking or climbing stairs'},
    'Sex': {1: 'Male', 2: 'Female'},
    'Age': {1: '18–24', 2: '25–29', 3: '30–34', 4: '35–39', 5: '40–44', 6: '45–49', 7: '50–54', 8: '55–59', 9: '60–64', 10: '65–69', 11: '70–74', 12: '75–79', 13: '80 or older'},
    'Education': {1: 'Never attended school or kindergarten only', 2: 'Grades 1–8', 3: 'Grades 9–11', 4: 'Grade 12 or GED', 5: 'College/technical school: 1–3 years', 6: 'College graduate: 4 or more years'},
    'Income': {1: 'Less than $10,000', 2: '$10,000 to <$15,000', 3: '$15,000 to <$20,000', 4: '$20,000 to <$25,000', 5: '$25,000 to <$35,000', 6: '$35,000 to <$50,000', 7: '$50,000 to <$75,000', 8: '$75,000 or more'},
    'InterviewDate': {'date': 'Interview date (cleaned to YYYY-MM-DD)'},
    'InterviewMonth': {1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June', 7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'},
    'InterviewDay': {'1–31': 'Day of month'},
    'InterviewYear': {2015: '2015', 2016: '2016'},
}

cols = pd.read_csv(f"{DATA_DIR}processed/heart_disease_health_indicators_BRFSS2015.csv").columns.tolist()

# Display one code-to-meaning table for each column present in the dataset.
for variable in cols:
    if variable in ['State']:
        df = create_state_df()
    else:
        mapping = variable_lookups.get(variable, {})
        rows = [{'Code / value': code, 'Meaning': meaning} for code, meaning in mapping.items()]
        display(Markdown(f'### {variable}'))
        df = pd.DataFrame(rows)
    display(df)

    raw_dir = Path(DATA_DIR) / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)
    output_path = raw_dir / f"{variable}.csv"
    df.to_csv(output_path, index=False)
    display(Markdown(f"Saved lookup table for {variable} to {output_path}"))

### HeartDiseaseorAttack

   Code / value                                            Meaning
0             0  No reported coronary heart disease or myocardi...
1             1  Reported coronary heart disease or myocardial ...

Saved lookup table for HeartDiseaseorAttack to ../../data/raw/HeartDiseaseorAttack.csv

### InterviewDate

  Code / value                                 Meaning
0         date  Interview date (cleaned to YYYY-MM-DD)

Saved lookup table for InterviewDate to ../../data/raw/InterviewDate.csv

### InterviewMonth

    Code / value    Meaning
0              1    January
1              2   February
2              3      March
3              4      April
4              5        May
5              6       June
6              7       July
7              8     August
8              9  September
9             10    October
10            11   November
11            12   December

Saved lookup table for InterviewMonth to ../../data/raw/InterviewMonth.csv

### InterviewDay

  Code / value       Meaning
0         1–31  Day of month

Saved lookup table for InterviewDay to ../../data/raw/InterviewDay.csv

### InterviewYear

   Code / value Meaning
0          2015    2015
1          2016    2016

Saved lookup table for InterviewYear to ../../data/raw/InterviewYear.csv

### HighBP

   Code / value Meaning
0             0      No
1             1     Yes

Saved lookup table for HighBP to ../../data/raw/HighBP.csv

### HighChol

   Code / value Meaning
0             0      No
1             1     Yes

Saved lookup table for HighChol to ../../data/raw/HighChol.csv

### CholCheck

   Code / value                                            Meaning
0             0  No cholesterol check in the past 5 years / nev...
1             1        Cholesterol checked within the past 5 years

Saved lookup table for CholCheck to ../../data/raw/CholCheck.csv

### BMI

  Code / value                                            Meaning
0      numeric  Body mass index in kg/m²; source _BMI5 is divi...

Saved lookup table for BMI to ../../data/raw/BMI.csv

### Smoker

   Code / value                                            Meaning
0             0  No: has not smoked at least 100 cigarettes in ...
1             1  Yes: has smoked at least 100 cigarettes in lif...

Saved lookup table for Smoker to ../../data/raw/Smoker.csv

### Stroke

   Code / value Meaning
0             0      No
1             1     Yes

Saved lookup table for Stroke to ../../data/raw/Stroke.csv

### Diabetes

   Code / value                                         Meaning
0             0  No diabetes, or diabetes only during pregnancy
1             1             Pre-diabetes or borderline diabetes
2             2                                   Yes, diabetes

Saved lookup table for Diabetes to ../../data/raw/Diabetes.csv

### PhysActivity

   Code / value                                            Meaning
0             0  No physical activity/exercise in past 30 days ...
1             1  Any physical activity/exercise in past 30 days...

Saved lookup table for PhysActivity to ../../data/raw/PhysActivity.csv

### Fruits

   Code / value                       Meaning
0             0  Fruit less than once per day
1             1   Fruit at least once per day

Saved lookup table for Fruits to ../../data/raw/Fruits.csv

### Veggies

   Code / value                            Meaning
0             0  Vegetables less than once per day
1             1   Vegetables at least once per day

Saved lookup table for Veggies to ../../data/raw/Veggies.csv

### HvyAlcoholConsump

   Code / value                                            Meaning
0             0                                  No heavy drinking
1             1  Heavy drinking (men >14 drinks/week; women >7 ...

Saved lookup table for HvyAlcoholConsump to ../../data/raw/HvyAlcoholConsump.csv

### AnyHealthcare

   Code / value                   Meaning
0             0   No health-care coverage
1             1  Has health-care coverage

Saved lookup table for AnyHealthcare to ../../data/raw/AnyHealthcare.csv

### NoDocbcCost

   Code / value                                            Meaning
0             0  Did not need to see a doctor but could not aff...
1             1  Could not afford to see a doctor in past 12 mo...

Saved lookup table for NoDocbcCost to ../../data/raw/NoDocbcCost.csv

### GenHlth

   Code / value    Meaning
0             1  Excellent
1             2  Very good
2             3       Good
3             4       Fair
4             5       Poor

Saved lookup table for GenHlth to ../../data/raw/GenHlth.csv

### MentHlth

  Code / value                                            Meaning
0            0               0 days mental health not good (none)
1         1–30  Number of days mental health was not good in t...
2           88                                               None
3           77                                Don't know/Not sure
4           99                                            Refused

Saved lookup table for MentHlth to ../../data/raw/MentHlth.csv

### PhysHlth

  Code / value                                            Meaning
0            0             0 days physical health not good (none)
1         1–30  Number of days physical health was not good in...
2           88                                               None
3           77                                Don't know/Not sure
4           99                                            Refused

Saved lookup table for PhysHlth to ../../data/raw/PhysHlth.csv

### DiffWalk

   Code / value                                           Meaning
0             0  No serious difficulty walking or climbing stairs
1             1     Serious difficulty walking or climbing stairs

Saved lookup table for DiffWalk to ../../data/raw/DiffWalk.csv

### Sex

   Code / value Meaning
0             1    Male
1             2  Female

Saved lookup table for Sex to ../../data/raw/Sex.csv

### Age

    Code / value      Meaning
0              1        18–24
1              2        25–29
2              3        30–34
3              4        35–39
4              5        40–44
5              6        45–49
6              7        50–54
7              8        55–59
8              9        60–64
9             10        65–69
10            11        70–74
11            12        75–79
12            13  80 or older

Saved lookup table for Age to ../../data/raw/Age.csv

### Education

   Code / value                                     Meaning
0             1  Never attended school or kindergarten only
1             2                                  Grades 1–8
2             3                                 Grades 9–11
3             4                             Grade 12 or GED
4             5         College/technical school: 1–3 years
5             6           College graduate: 4 or more years

Saved lookup table for Education to ../../data/raw/Education.csv

### Income

   Code / value              Meaning
0             1    Less than $10,000
1             2  $10,000 to <$15,000
2             3  $15,000 to <$20,000
3             4  $20,000 to <$25,000
4             5  $25,000 to <$35,000
5             6  $35,000 to <$50,000
6             7  $50,000 to <$75,000
7             8      $75,000 or more

Saved lookup table for Income to ../../data/raw/Income.csv

    Code / value               Meaning
0              1               Alabama
1              2                Alaska
2              4               Arizona
3              5              Arkansas
4              6            California
5              8              Colorado
6              9           Connecticut
7             10              Delaware
8             11  District of Columbia
9             12               Florida
10            13               Georgia
11            15                Hawaii
12            16                 Idaho
13            17              Illinois
14            18               Indiana
15            19                  Iowa
16            20                Kansas
17            21              Kentucky
18            22             Louisiana
19            23                 Maine
20            24              Maryland
21            25         Massachusetts
22            26              Michigan
23            27             Minnesota
24            28           Mississippi
25            29              Missouri
26            30               Montana
27            31              Nebraska
28            32                Nevada
29            33         New Hampshire
30            34            New Jersey
31            35            New Mexico
32            36              New York
33            37        North Carolina
34            38          North Dakota
35            39                  Ohio
36            40              Oklahoma
37            41                Oregon
38            42          Pennsylvania
39            44          Rhode Island
40            45        South Carolina
41            46          South Dakota
42            47             Tennessee
43            48                 Texas
44            49                  Utah
45            50               Vermont
46            51              Virginia
47            53            Washington
48            54         West Virginia
49            55             Wisconsin
50            56               Wyoming
51            66                  Guam
52            72           Puerto Rico

Saved lookup table for State to ../../data/raw/State.csv

### BMICategory

  Code / value          Meaning
0  Underweight       BMI < 18.5
1       Normal  18.5 ≤ BMI < 25
2   Overweight    25 ≤ BMI < 30
3      Obesity         BMI ≥ 30

Saved lookup table for BMICategory to ../../data/raw/BMICategory.csv